### ISSUE TITLE
Error setup config for local 

### ISSUE THREAD

**Issue by archagy** [aaronshaf/dynamodb-admin#10] opened 2017-07-05 16:32 UTC
Trying to use dynamodb for local dev. But I got the following error.

```
{
  "error": {
    "message": "Not Found",
    "code": "UnknownError",
    "statusCode": 404,
    "time": "2017-07-05T16:28:04.788Z",
    "retryable": false,
    "retryDelay": 49.88090401504783
  }
}
```

I use this conf

export AWS_SECRET_ACCESS_KEY=mysecret
export AWS_ACCESS_KEY_ID=myaccess
export AWS_REGION=myregion

Also with this:
export AWS_SECRET_ACCESS_KEY=local                                                             
export AWS_ACCESS_KEY_ID=local                                                              
export DYNAMO_ENDPOINT=http://localhost:8000 

Many thanks

**Comment by archagy** [comment] 2017-07-05 17:45
I solve this with this. On DYNAMO_ENDPOINT should be the localhost port of dynamodb. In my case :3030. 

Hope this helps someone.

**Comment by MatheusVellone** [comment] 2017-08-23 18:17
Closing the issue, as the problem is solved :)

**Closed by MatheusVellone** 2017-08-23 18:17 UTC
